import = [
    "~/.dotfiles/config/alacritty/color_schemas/argonaut.toml"
]

[colors.primary]
background = "0x101421"
foreground = "0xfffbf6"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "Cica"
style = "Bold"

[font.normal]
family = "Cica"
style = "Regular"

[window]
opacity = 0.75
decorations = "Full"

[shell]
program = "/bin/zsh"
args = [ "-l",
	 "-c",
	 "tmux a -t default || tmux a -t base || tmux new -s base"]
