typeset -U path cdpath fpath manpath

for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/k8q05xwqhn15xzyx5klbbry21i54xjsp-zsh-5.9/share/zsh/$ZSH_VERSION/help"

autoload -U compinit && compinit
# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="/Users/rkarsnk/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK

# Enabled history options
enabled_opts=(
  HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY
)
for opt in "${enabled_opts[@]}"; do
  setopt "$opt"
done
unset opt enabled_opts

# Disabled history options
disabled_opts=(
  APPEND_HISTORY EXTENDED_HISTORY HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS
  HIST_IGNORE_ALL_DUPS HIST_SAVE_NO_DUPS
)
for opt in "${disabled_opts[@]}"; do
  unsetopt "$opt"
done
unset opt disabled_opts

# Prompt Configを読み込む
if [[ ! $TERM == xterm  ]] then
    sharp='\uE0B0'
    
    user="%K{white}%F{red}%B%n@%m %b%f%k%F{white}%K{blue}${sharp} %k%f"
    curdir="%K{blue}%F{white}%B%~%b %#%f %k%F{blue}${sharp}%f"

    PROMPT=`echo $user$curdir\ `
else
    PROMPT=`echo '[%n@%m %#] '`
fi

# Aliases
case ${OSTYPE} in
	darwin*)
		alias ls='ls -G'
		;;
	linux*)
		alias ls='ls --color=auto'
		;;
esac

# cp,mv,rm alias
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# date alias
alias today='date "+%Y-%m-%d"'
alias timestamp='date "+%Y%m%d"'
alias now='date "+%Y-%m-%d %a %H:%M:%S %Z"'

# bindkey for vim keybindings
bindkey -e # Enable emacs keybindings
bindkey -r '^J' # Ctrl-j

